# TODO: When we get the ability to reference workflows from other repos, this one should pull in the ones from
# each driver instead of this incomplete reimplementation of each one.
# See https://github.community/t/is-it-possible-to-use-the-same-workflow-in-different-repositories/17719/6
name: test
on:
  pull_request:
  push: 
    branches: 
      - main
      - master
jobs:
  dependents:
    runs-on: ubuntu-latest
    services:
      mysql-a:
        image: mysql:latest
        env: 
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
      mysql-b:
        image: mysql:latest
        env: 
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_USER: vapor_username
          MYSQL_PASSWORD: vapor_password
          MYSQL_DATABASE: vapor_database
      postgres-a:
        image: postgres:latest
        env:
          POSTGRES_USER: vapor_username
          POSTGRES_PASSWORD: vapor_password
          POSTGRES_DB: vapor_database
      postgres-b:
        image: postgres:latest
        env: 
          POSTGRES_USER: vapor_username
          POSTGRES_PASSWORD: vapor_password
          POSTGRES_DB: vapor_database
      mongo-a:
        image: mongo:latest
      mongo-b:
        image: mongo:latest
    container: swift:5.2-bionic
    strategy:
      fail-fast: false
      matrix:
        dependent:
          - fluent-sqlite-driver
          - fluent-postgres-driver
          - fluent-mysql-driver
          - fluent-mongo-driver
    steps:
      - name: Install SQLite dependencies
        run: apt-get -q update && apt-get -q install -y libsqlite3-dev
        if: ${{ contains(matrix.dependent, 'sqlite') }}
      - name: Check out package
        uses: actions/checkout@v2
        with:
          path: package
      - name: Check out dependent
        uses: actions/checkout@v2
        with:
          repository: vapor/${{ matrix.dependent }}
          path: dependent
      - name: Use local package
        run: swift package edit fluent-kit --path ../package
        working-directory: dependent
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
        working-directory: dependent
        env:
          POSTGRES_HOSTNAME_A: postgres-a
          POSTGRES_HOSTNAME_B: postgres-b
          MYSQL_HOSTNAME_A: mysql-a
          MYSQL_HOSTNAME_B: mysql-b
          MONGO_HOSTNAME_A: mongo-a
          MONGO_HOSTNAME_B: mongo-b
          LOG_LEVEL: info
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          # 5.2 Stable
          - swift:5.2-bionic
          # 5.2 Unstable
          - swiftlang/swift:nightly-5.2-bionic
          # 5.3 Unstable
          - swiftlang/swift:nightly-5.3-bionic
          # Master Unsable
          # Temporarily disabled because master has
          # been broken for ages
          # - swiftlang/swift:nightly-master-focal
    container: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
  macOS:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@1.0
        with: 
          xcode-version: latest
      - name: Check out package
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        run: swift test --enable-test-discovery --sanitize=thread
        env:
          LOG_LEVEL: info
  build:
    runs-on: macOS-latest
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=13.0,name=iPhone 11']
            xcode: ['/Applications/Xcode_11.5.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
    # Github Actions' machines do in fact have recent versions of Xcode,
    # but you may have to explicitly switch to them.  We explicitly want
    # to use Xcode 11.5, so we use xcode-select to switch to it.
    - name: Switch to Xcode 11.5
      run: sudo xcode-select --switch /Applications/Xcode_11.5.app
    # Since we want to be running our tests from Xcode, we need to
    # generate an .xcodeproj file.  Luckly, Swift Package Manager has
    # build in functionality to do so.
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    # Finally, we invoke xcodebuild to run the tests on an iPhone 11
    # simulator.
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'fluent-kit-Package'
